# Generated by Django 5.0.2 on 2024-02-28 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_parked', models.BooleanField(default=False)),
                ('owner', models.CharField(max_length=20)),
                ('maker', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('plate', models.CharField(max_length=6, unique=True)),
                ('space', models.CharField(max_length=30)),
                ('entry', models.DateTimeField(auto_now_add=True)),
                ('exit', models.DateTimeField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=5, max_digits=12)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
